CREATE TABLE [dbo].[Command]
(
	[CommandID] INT NOT NULL PRIMARY KEY IDENTITY,
	[UserID] INT NOT NULL,
	[IsPaid] BIT NOT NULL DEFAULT 0,
	[DateCommande] DATETIME NOT NULL, 
    CONSTRAINT [FK_Command_User] FOREIGN KEY ([UserID]) REFERENCES [User]([UserID]) 

)
