CREATE TABLE [dbo].[User]
(
	[UserId] INT NOT NULL PRIMARY KEY IDENTITY,
	[Nom] VARCHAR(50) NOT NULL,
	[Prenom] VARCHAR(50) NOT NULL,
	[Email] NVARCHAR (255) NOT NULL UNIQUE,
	[MDP] NVARCHAR (MAX) NOT NULL,
	[Telephone] VARCHAR(50) NOT NULL,
	[Adresse] VARCHAR(MAX) NOT NULL,
	[IsAdmin] BIT NOT NULL DEFAULT 0,


)
